use_frameworks!
platform :ios, '9.0'

target 'CCPAConsentViewController_Example' do
  pod 'CCPAConsentViewController', :path => '../'
  pod 'SwiftLint'
end

target 'CCPAConsentViewController_ExampleTests' do
  pod 'CCPAConsentViewController', :path => '../'
  pod 'Quick'
  pod 'Nimble'
end

target 'AuthExample' do
  pod 'CCPAConsentViewController', :path => '../'
end

target 'SourcePointMetaApp' do
  pod 'CCPAConsentViewController', :path => '../'
  pod 'IQKeyboardManagerSwift'
end

target 'SourcePointMetaAppTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'CCPAConsentViewController', :path => '../'
end
