name: Swift
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing SwiftLint
        run: brew install swiftlint
      - name: linting
        run: cd Example && swiftlint lint
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: CocoaPod Install
        run: cd Example && pod install
      - name: Example app Unit and UI testing -> iPhone 11 (iOS 13.7)
        run: xcodebuild test -scheme ConsentViewController-Example -workspace Example/CCPAConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.7' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
      - name: SourcePointMetaApp UI testing -> iPhone 11 (iOS 13.7)
        run: xcodebuild test -scheme SourcePointMetaApp -workspace Example/CCPAConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.7' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

